name: bugsinpy-testall

on: workflow_dispatch

jobs:
  testall:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image bugsinpy-testall
      run: |
        docker build . --file Dockerfile --tag bugsinpy-testall:Dockerfile
